name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.rp.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp

  deploy-into-production:
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs.release-created }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: Production
